services:
  rails:
    build:
      context: ../railsApp
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ../railsApp/.env.production
    environment:
      RAILS_ENV: development
    volumes:
      - ../railsApp:/app           # live code
      - bundle:/usr/local/bundle   # persist gems
      - rails_tmp:/app/tmp         # fewer perms issues
    # In dev we want the python agent available for feature testing.
    depends_on:
      - redis
      - agent

  agent:
    build:
      context: ../python
      dockerfile: Dockerfile
    working_dir: /app
    command: python main.py
    env_file:
      - ../railsApp/.env.production
    volumes:
      - ../python:/app     # live code
    depends_on:
      - redis
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 2s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  bundle:
  rails_tmp: