name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/ci.yml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # Helper step definition reused via YAML anchors is not supported by Actions,
  # so we repeat the short "locate dir" snippet in each job.

  scan_ruby:
    name: scan_ruby
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Locate Rails app dir
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          for d in backend/railsApp backend/rails railsApp rails; do
            if [ -f "$d/Gemfile" ]; then
              echo "APP_DIR=$d" >> "$GITHUB_ENV"
              echo "Found Rails at: $d"
              exit 0
            fi
          done
          echo "❌ Could not find Rails app directory. Repo layout:" >&2
          ls -la
          echo "--- backend:" >&2
          ls -la backend || true
          exit 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Brakeman (Rails security scan)
        shell: bash
        run: |
          cd "$APP_DIR"
          bin/brakeman --no-pager

  scan_js:
    name: scan_js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Locate Rails app dir
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          for d in backend/railsApp backend/rails railsApp rails; do
            if [ -f "$d/Gemfile" ]; then
              echo "APP_DIR=$d" >> "$GITHUB_ENV"
              echo "Found Rails at: $d"
              exit 0
            fi
          done
          echo "❌ Could not find Rails app directory. Repo layout:" >&2
          ls -la
          echo "--- backend:" >&2
          ls -la backend || true
          exit 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Importmap audit (JS deps)
        shell: bash
        run: |
          cd "$APP_DIR"
          bin/importmap audit

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Locate Rails app dir
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          for d in backend/railsApp backend/rails railsApp rails; do
            if [ -f "$d/Gemfile" ]; then
              echo "APP_DIR=$d" >> "$GITHUB_ENV"
              echo "Found Rails at: $d"
              exit 0
            fi
          done
          echo "❌ Could not find Rails app directory. Repo layout:" >&2
          ls -la
          echo "--- backend:" >&2
          ls -la backend || true
          exit 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      - name: Rubocop
        shell: bash
        run: |
          cd "$APP_DIR"
          bin/rubocop -f github

  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: rails
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U rails -d app_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20
    steps:
      - uses: actions/checkout@v4

      - name: Locate Rails app dir
        id: locate
        shell: bash
        run: |
          set -euo pipefail
          for d in backend/railsApp backend/rails railsApp rails; do
            if [ -f "$d/Gemfile" ]; then
              echo "APP_DIR=$d" >> "$GITHUB_ENV"
              echo "Found Rails at: $d"
              exit 0
            fi
          done
          echo "❌ Could not find Rails app directory. Repo layout:" >&2
          ls -la
          echo "--- backend:" >&2
          ls -la backend || true
          exit 1

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      # If you run system tests needing a browser, add Chrome install here.

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://rails:rails@localhost:5432/app_test
          REDIS_URL: redis://localhost:6379/0
        shell: bash
        run: |
          cd "$APP_DIR"
          bin/rails db:test:prepare
          bin/rails test

      - name: Upload failed screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: ${{ env.APP_DIR }}/tmp/screenshots
          if-no-files-found: ignore