name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/railsApp/**'
      - '.github/workflows/ci.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/railsApp/**'
      - '.github/workflows/ci.yml'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  # ---------------------- scan_ruby ----------------------
  scan_ruby:
    name: scan_ruby
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/railsApp
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true
      - name: Brakeman (Rails security scan)
        run: bin/brakeman --no-pager

  # ---------------------- scan_js ----------------------
  scan_js:
    name: scan_js
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/railsApp
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true
      - name: Importmap audit (JS deps)
        run: bin/importmap audit

  # ------------------------ lint -----------------------
  lint:
    name: lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/railsApp
    steps:
      - uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true
      - name: Rubocop
        run: bin/rubocop -f github

  # ------------------------ test -----------------------
  test:
    name: test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: rails
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U rails -d app_test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=20
    defaults:
      run:
        working-directory: backend/railsApp
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.6'
          bundler-cache: true

      # If you run system tests needing a browser, uncomment:
      # - name: Install Chrome for system tests
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install --no-install-recommends -y google-chrome-stable

      - name: Run tests
        env:
          RAILS_ENV: test
          # CI DB is a local ephemeral Postgres service
          DATABASE_URL: postgres://rails:rails@localhost:5432/app_test
          REDIS_URL: redis://localhost:6379/0
        run: |
          bin/rails db:test:prepare
          bin/rails test

      - name: Upload failed screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: backend/railsApp/tmp/screenshots
          if-no-files-found: ignore